/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BD.Conexion;
import customade2.Entidades.*;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.util.Base64;
import java.util.Iterator;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
/**
 *
 * @author jsmat
 */
public class PanelInicial extends javax.swing.JFrame {

    /**
     * Creates new form PanelInicial
     */
    public PanelInicial() {
        initComponents();
//        jLabel4.setText("<html><a href='www.google.com'>google</a></html>");
       Refresh();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaPedidos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDetalles = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jBotonDiseños = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDiseños = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableImagen = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        jComboBox1.setModel(new DefaultComboBoxModel(EstadoPedido.values()));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(855, 465));

        jTablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "Fecha Pedido", "Nombre Completo Cliente", "CI Cliente", "Telefono Cliente", "Email Cliente", "Dirección Cliente", "Estado del Pedido", "Precio Total", "Obejto", "Detalle Pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablaPedidos.setColumnSelectionAllowed(true);
        jTablaPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablaPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablaPedidos);
        jTablaPedidos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTablaPedidos.getColumnModel().getColumnCount() > 0) {
            jTablaPedidos.getColumnModel().getColumn(9).setMinWidth(0);
            jTablaPedidos.getColumnModel().getColumn(9).setPreferredWidth(0);
            jTablaPedidos.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        jButton1.setText("Actualizar Estado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Precio Unitario", "Objeto"
            }
        ));
        jScrollPane2.setViewportView(jTableDetalles);

        jButton2.setText("Ver Detalles de pedido");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBotonDiseños.setText("Ver Diseños");
        jBotonDiseños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonDiseñosActionPerformed(evt);
            }
        });

        jTableDiseños.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre Diseño", "Precio Unitario", "Imagen"
            }
        ));
        jScrollPane3.setViewportView(jTableDiseños);

        jTableImagen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Posicion BACK O FRONT", "Margen Izquierdo", "Margen de arriba", "Ancho", "Largo", "Imagen"
            }
        ));
        jScrollPane4.setViewportView(jTableImagen);

        jButton3.setText("Ver Imágenes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mostra Imagen");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Descargar Imagen");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(6, 6, 6))
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBotonDiseños, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBotonDiseños)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(259, 259, 259)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(27, 27, 27))))
        );

        jScrollPane5.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTablaPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablaPedidosMouseClicked
       
    }//GEN-LAST:event_jTablaPedidosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pedido p = (Pedido) jTablaPedidos.getValueAt(jTablaPedidos.getSelectedRow(),9);
        p.setEstado((EstadoPedido) jTablaPedidos.getValueAt(jTablaPedidos.getSelectedRow(),7));
        if (p.getEstado() == EstadoPedido.FINALIZADO) {
            List<DetalleDePedido> detalles = p.getDetalleDePedidos();
            for (Iterator<DetalleDePedido> iterator = detalles.iterator(); iterator.hasNext();) {
                DetalleDePedido next = iterator.next();
                Articulo a = next.getDisneioDelDetalle().getArticulo();
                a.setStock(a.getStock()-next.getCantidad());
                Conexion.getInstance().merge(a);
            }
        }
        Conexion.getInstance().merge(p);
        Refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         Pedido p = (Pedido) jTablaPedidos.getValueAt(jTablaPedidos.getSelectedRow(),9);
            List<DetalleDePedido> detalles = p.getDetalleDePedidos();
             DefaultTableModel md2 = (DefaultTableModel) jTableDetalles.getModel();
            for (Iterator<DetalleDePedido> iterator = detalles.iterator(); iterator.hasNext();) {
                DetalleDePedido next = iterator.next();
                Object[] fila = new Object[3];
                fila[0] = next.getCantidad();
                fila[1] = next.getPrecioUnitario();
                fila[2] = next;
                md2.addRow(fila);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBotonDiseñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonDiseñosActionPerformed
        DetalleDePedido p = (DetalleDePedido) jTableDetalles.getValueAt(jTableDetalles.getSelectedRow(),2);
             DefaultTableModel md2 = (DefaultTableModel) jTableDiseños.getModel();
             md2.setRowCount(0);
             Object[] fila = new Object[3];
             fila[0] = p.getDisneioDelDetalle().getNombre();
             fila[1] = p.getDisneioDelDetalle().getPrecioUnitario();
             fila[2] = p.getDisneioDelDetalle();
                md2.addRow(fila);
       
                // TODO add your handling code here:
    }//GEN-LAST:event_jBotonDiseñosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Disenio d = (Disenio) jTableDiseños.getValueAt(jTableDiseños.getSelectedRow(),2);
         DefaultTableModel md2 = (DefaultTableModel) jTableImagen.getModel();
       List<Imagen> detalles = d.getImagens();
            for (Iterator<Imagen> iterator = detalles.iterator(); iterator.hasNext();) {
                Imagen next = iterator.next();
                Object[] fila = new Object[7];
                fila[0] = next.getId();
                fila[1] = next.getPosicionBackFront();
                fila[2] = next.getMarginLeft();
                fila[3] = next.getMarginTop();
                fila[4] = next.getAncho();
                fila[5] = next.getLargo();
                fila[6] = next;
                md2.addRow(fila);
        }
              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Imagen i = (Imagen) jTableImagen.getValueAt(jTableImagen.getSelectedRow(), 6);
//        byte[] imgFront = i.getImagenProporcionada();    
//       byte[] encodedFront = Base64.getEncoder().encode(imgFront);
//       String imgFrontstr = "data:image/jpeg;base64,"+ (new String(encodedFront));
        Image aux = new ImageIcon(i.getImagenProporcionada()).getImage();
        ImageIcon aux1 = new ImageIcon(i.getImagenProporcionada());
        ImageIcon perfil = new ImageIcon(aux.getScaledInstance(400, 400*(aux1.getIconWidth()/aux1.getIconHeight()), Image.SCALE_DEFAULT)); //formula relacion aspecto
       jLabelImage.setIcon(perfil);
//       jLabelImage.setText("<html><img src="+imgFrontstr+"\">");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    Imagen i = (Imagen) jTableImagen.getValueAt(jTableImagen.getSelectedRow(), 6);
        FileInputStream fileInputStream = null;
//		File file = new File("C:\\FileTests\\Cliente-servidor-1.jpg");
//		byte[] fileArray = new byte[(int) file.length()];
                

		try {
			// Con este código se obtienen los bytes del archivo.
//			fileInputStream = new FileInputStream(file);
//			fileInputStream.read(fileArray);
//			fileInputStream.close();

			// Con este código se agregan los bytes al archivo.
                        String homeUsuario = System.getProperty("user.home");
			FileOutputStream fileOuputStream = new FileOutputStream(homeUsuario+"\\"+i.getDisenio().getNombre()+".jpg");
                        fileOuputStream.write(i.getImagenProporcionada());
			fileOuputStream.close();
                        JOptionPane.showMessageDialog(this,"Imágen descargada con éxito.");
                        Desktop.getDesktop().open(new File(homeUsuario+"\\"+i.getDisenio().getNombre()+".jpg"));

		} catch (Exception e) {
			//Manejar Error
		}
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelInicial().setVisible(true);
                
            }
        });
    }
    private void Refresh(){
         TableColumn testColumn = jTablaPedidos.getColumnModel().getColumn(7);
        testColumn.setCellEditor(new DefaultCellEditor(jComboBox1));
        
        Iterator<Pedido> it = Conexion.getInstance().select("FROM Pedido", Pedido.class).iterator();
        DefaultTableModel mdl = (DefaultTableModel) jTablaPedidos.getModel();
        mdl.setRowCount(0);
        while (it.hasNext()) {
            Pedido next = it.next();
            Object[] fila = new Object[11];
            fila[0] = next.getId();
            fila[1] = next.getFecha();
            fila[2] = next.getNombreCompletoCliente();
            fila[3] = next.getTelefonoCliente();
            fila[4] = next.getCiCliente();
            fila[5] = next.getEmailCliente();
            fila[6] = next.getDireccionCLiente();
            fila[7] = next.getEstado();
            fila[8] = next.getPrecioTotal();
            fila[9] = next;
            fila[10] = next.getDetalleDePedidos();
            mdl.addRow(fila);
            
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonDiseños;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTablaPedidos;
    private javax.swing.JTable jTableDetalles;
    private javax.swing.JTable jTableDiseños;
    private javax.swing.JTable jTableImagen;
    // End of variables declaration//GEN-END:variables
}
